global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'forever-home'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # Use host-gateway for Linux Docker to reach host machine
      - targets: ['host-gateway:8080']
