-- V29: Add new breed values to constraint
-- Expands the breed enum with additional common dog and cat breeds

-- Drop the existing constraint
ALTER TABLE pets DROP CONSTRAINT IF EXISTS chk_pets_breed;

-- Add updated CHECK constraint with all breed values
ALTER TABLE pets ADD CONSTRAINT chk_pets_breed CHECK (
    breed IS NULL OR breed IN (
        -- Dog breeds (35 total)
        'LABRADOR', 'GOLDEN_RETRIEVER', 'GERMAN_SHEPHERD', 'FRENCH_BULLDOG', 'BULLDOG',
        'BEAGLE', 'POODLE', 'POODLE_MIX', 'ROTTWEILER', 'YORKSHIRE_TERRIER',
        'BOXER', 'DACHSHUND', 'HUSKY', 'SIBERIAN_HUSKY', 'GREAT_DANE',
        'DOBERMAN', 'AUSTRALIAN_SHEPHERD', 'CAVALIER_KING_CHARLES', 'SHIH_TZU', 'BOSTON_TERRIER',
        'BERNESE_MOUNTAIN_DOG', 'POMERANIAN', 'HAVANESE', 'SHETLAND_SHEEPDOG', 'CORGI',
        'PEMBROKE_WELSH_CORGI', 'COCKER_SPANIEL', 'BORDER_COLLIE', 'CHIHUAHUA', 'MINIATURE_SCHNAUZER',
        'PIT_BULL', 'MALTESE', 'JACK_RUSSELL_TERRIER', 'BICHON_FRISE', 'MIXED_DOG',
        -- Cat breeds (25 total)
        'TABBY', 'DOMESTIC_SHORTHAIR', 'DOMESTIC_LONGHAIR', 'SIAMESE', 'MAINE_COON',
        'PERSIAN', 'RAGDOLL', 'BENGAL', 'BRITISH_SHORTHAIR', 'ABYSSINIAN',
        'BIRMAN', 'ORIENTAL_SHORTHAIR', 'SPHYNX', 'DEVON_REX', 'SCOTTISH_FOLD',
        'RUSSIAN_BLUE', 'AMERICAN_SHORTHAIR', 'NORWEGIAN_FOREST_CAT', 'EXOTIC_SHORTHAIR', 'BURMESE',
        'TONKINESE', 'HIMALAYAN', 'TURKISH_ANGORA', 'RAGAMUFFIN', 'MIXED_CAT'
    )
);
